DROP TABLE IF EXISTS `follow`;
DROP TABLE IF EXISTS `favorite`;
DROP TABLE IF EXISTS `answer`;
DROP TABLE IF EXISTS `question`;
DROP TABLE IF EXISTS `tag`;
DROP TABLE IF EXISTS `post_content`;
DROP TABLE IF EXISTS `post`;
DROP TABLE IF EXISTS `user`;
