package com.tongji.weshare.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table post
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Post implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_id
     *
     * @mbg.generated
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.poster_id
     *
     * @mbg.generated
     */
    private Integer posterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.star_num
     *
     * @mbg.generated
     */
    private Integer starNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.views
     *
     * @mbg.generated
     */
    private Integer views;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_id
     *
     * @return the value of post.post_id
     *
     * @mbg.generated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_id
     *
     * @param postId the value for post.post_id
     *
     * @mbg.generated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.poster_id
     *
     * @return the value of post.poster_id
     *
     * @mbg.generated
     */
    public Integer getPosterId() {
        return posterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.poster_id
     *
     * @param posterId the value for post.poster_id
     *
     * @mbg.generated
     */
    public void setPosterId(Integer posterId) {
        this.posterId = posterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.title
     *
     * @return the value of post.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.title
     *
     * @param title the value for post.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.star_num
     *
     * @return the value of post.star_num
     *
     * @mbg.generated
     */
    public Integer getStarNum() {
        return starNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.star_num
     *
     * @param starNum the value for post.star_num
     *
     * @mbg.generated
     */
    public void setStarNum(Integer starNum) {
        this.starNum = starNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.views
     *
     * @return the value of post.views
     *
     * @mbg.generated
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.views
     *
     * @param views the value for post.views
     *
     * @mbg.generated
     */
    public void setViews(Integer views) {
        this.views = views;
    }
}