package com.tongji.weshare.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table answer
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Answer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.answer_id
     *
     * @mbg.generated
     */
    private Integer answerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.question_id
     *
     * @mbg.generated
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.answerer_id
     *
     * @mbg.generated
     */
    private Integer answererId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.star_num
     *
     * @mbg.generated
     */
    private Integer starNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.answer_id
     *
     * @return the value of answer.answer_id
     *
     * @mbg.generated
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.answer_id
     *
     * @param answerId the value for answer.answer_id
     *
     * @mbg.generated
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.question_id
     *
     * @return the value of answer.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.question_id
     *
     * @param questionId the value for answer.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.answerer_id
     *
     * @return the value of answer.answerer_id
     *
     * @mbg.generated
     */
    public Integer getAnswererId() {
        return answererId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.answerer_id
     *
     * @param answererId the value for answer.answerer_id
     *
     * @mbg.generated
     */
    public void setAnswererId(Integer answererId) {
        this.answererId = answererId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.star_num
     *
     * @return the value of answer.star_num
     *
     * @mbg.generated
     */
    public Integer getStarNum() {
        return starNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.star_num
     *
     * @param starNum the value for answer.star_num
     *
     * @mbg.generated
     */
    public void setStarNum(Integer starNum) {
        this.starNum = starNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.content
     *
     * @return the value of answer.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.content
     *
     * @param content the value for answer.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }
}