package com.tongji.weshare.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table follow
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Follow implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.follower_id
     *
     * @mbg.generated
     */
    private Integer followerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.followed_user_id
     *
     * @mbg.generated
     */
    private Integer followedUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table follow
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.follower_id
     *
     * @return the value of follow.follower_id
     *
     * @mbg.generated
     */
    public Integer getFollowerId() {
        return followerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.follower_id
     *
     * @param followerId the value for follow.follower_id
     *
     * @mbg.generated
     */
    public void setFollowerId(Integer followerId) {
        this.followerId = followerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.followed_user_id
     *
     * @return the value of follow.followed_user_id
     *
     * @mbg.generated
     */
    public Integer getFollowedUserId() {
        return followedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.followed_user_id
     *
     * @param followedUserId the value for follow.followed_user_id
     *
     * @mbg.generated
     */
    public void setFollowedUserId(Integer followedUserId) {
        this.followedUserId = followedUserId;
    }
}