package com.tongji.weshare.mapper;

import com.tongji.weshare.entity.PostContent;
import com.tongji.weshare.entity.PostContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface PostContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    long countByExample(PostContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    int deleteByExample(PostContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("postId") Integer postId, @Param("floor") Integer floor);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    int insert(PostContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    int insertSelective(PostContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    List<PostContent> selectByExampleWithBLOBs(PostContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    List<PostContent> selectByExample(PostContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    PostContent selectByPrimaryKey(@Param("postId") Integer postId, @Param("floor") Integer floor);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PostContent record, @Param("example") PostContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PostContent record, @Param("example") PostContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PostContent record, @Param("example") PostContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PostContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PostContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PostContent record);
}